version: '3'
services:
  statsd:
    container_name: statsd
    image: graphiteapp/graphite-statsd
    ports:
      - "3002:80"
      - "2003:2003"
      - "8125:8125/udp"
      - "8126:8126"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"

