{
 "title": "Home Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "WIFI download bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    { "target": "stats.gauges.wifi.*.download" }
   ]
  },
  {
   "title": "WIFI upload bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    { "target": "stats.gauges.wifi.*.upload" }
   ]
  },
  {
   "title": "Ethernet download bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "target": "stats.gauges.ethernet.*.download"
    }
   ]
  },
  {
   "title": "Ethernet upload bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    { "target": "stats.gauges.ethernet.*.upload" }
   ]
  }
 ]
}